host = "localhost"
port = 8081
cache = "context.cache"

[site]
host = ""     # host of the website
username = "" # website username
password = "" # website password

[client.telegram]
host = "localhost"
port = 8080
