host = "localhost"
port = 8081

cache = "events.cache"   # event cache
authcache = "auth.cache" # authentication cache

frequency = 30_000 # poll frequency in ms

[site]
host = ""     # host of the website
username = "" # website username
password = "" # website password

[client.telegram]
host = "localhost"
port = 8080
