cache = "events.cache"   # event cache
authcache = "auth.cache" # authentication cache

frequency = 30 # poll frequency in s

[api]
host = "localhost"
port = 8081

[site]
host = ""     # host of the website
username = "" # website username
password = "" # website password

[client.telegram]
host = "localhost"
port = 8080
